### ISSUE TITLE
Cannot activate bread

### ISSUE THREAD

**Issue by dgershman** [bmlt-enabled/bread#208]
We are getting an error after upgrading to PHP 8.1.  Not sure how to resolve this.

```log
[Wed Mar 20 19:23:33.327014 2024] [php:error] [pid 1116] [client 120.205.61.122:12659] PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/ncregion/wp-content/plugins/bread/lang/translate_fa.php:6\nStack trace:\n#0 /var/www/ncregion/wp-content/plugins/bread/bmlt-meeting-list.php(322): include()\n#1 /var/www/ncregion/wp-content/plugins/bread/bmlt-meeting-list.php(114): Bread->load_translations()\n#2 /var/www/ncregion/wp-content/plugins/bread/bmlt-meeting-list.php(2939): Bread->__construct()\n#3 /var/www/ncregion/wp-settings.php(418): include_once('...')\n#4 /var/www/ncregion/wp-config.php(100): require_once('...')\n#5 /var/www/ncregion/wp-load.php(50): require_once('...')\n#6 /var/www/ncregion/wp-blog-header.php(13): require_once('...')\n#7 /var/www/ncregion/index.php(17): require('...')\n#8 {main}\n  thrown in /var/www/ncregion/wp-content/plugins/bread/lang/translate_fa.php on line 6
```

**Comment by dgershman** [comment]
Nevermind problem solved `apt-get install php-mbstring`.
