### ISSUE TITLE
Temp file write issue with some of the profile exports

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bread#64]
Fatal error: Uncaught Mpdf\MpdfException: Temporary files directory "/var/www/html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Config/../../tmp" is not writable in /var/www/html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Cache.php:17 Stack trace: #0 /var/www/html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/ServiceFactory.php(60): Mpdf\Cache->__construct('/var/www/html/w...') 
#1 /var/www/html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Mpdf.php(1043): Mpdf\ServiceFactory->getServices(Object(Mpdf\Mpdf), Object(Psr\Log\NullLogger), Array, 0, Object(Mpdf\Language\LanguageToFont), Object(Mpdf\Language\ScriptToLanguage), NULL, NULL, NULL, NULL) 
#2 /var/www/html/wp-content/plugins/bread/bmlt-meeting-list.php(713): Mpdf\Mpdf->__construct(Array)
#3 /var/www/html/wp-content/plugins/bread/bmlt-meeting-list.php(53): Bread->bmlt_meeting_list()
#4 /var/www/html/wp-content/plugins/bread/bmlt-meeting-list.php(2163): Bread->__construct() 
#5 /var/www/html/wp-settings.php(305): include_once('/var/www/html/w...') in /var/www/html/wp-content/plugins/bread/mpdf/vendor/mpdf/mpdf/src/Cache.php on line 17

**Comment by radius314** [comment]
related to some changes in the temp file writing.
